Add cookbook to table: Multi-lingual Customer Support Response Pipeline
instill-ai/cookbook pull request #19
Opened 2024-10-31 13:33 UTC by Ritesh-Udgata

This pull request Adds another example to the cookbook table showcasing how we can use instill to make multi-lingual customer support response pipeline.

2024-10-31 17:33 UTC, Ritesh-Udgata commented
please review this before mid night

2024-10-31 18:59 UTC, Ritesh-Udgata commented
Kindly add hacktoberfest topic to your repo or add hacktoberfest accepted to this pull request.

2024-10-31 21:43 UTC, GeorgeWilliamStrong commented on examples/Multi_Lingual_Customer_Support_Response_Pipeline.ipynb
> +        "from instill_sdk import InstillCoreClient\n",
```suggestion
        "from instill_sdk import InstillCoreClient\n",
```
This is not how to use our SDK. Please refer to our [documentation](https://www.instill.tech/docs/sdk/python).

```Python
from instill.clients import init_core_client

client = init_core_client(api_token="instill_sk_***")
```

2024-10-31 21:47 UTC, GeorgeWilliamStrong commented
Thank you for your PR! Please see the following feedback:

This notebook currently doesn't make use of any Instill AI services. If you want this to be accepted to our cookbook, please can you create a relevant VDP pipeline and update it to call that pipeline. Please also ensure that the formatting and style is consistent with the other examples in the cookbook repo.

2024-10-31 21:48 UTC, GeorgeWilliamStrong requested changes
Please address my comments

2024-11-01 06:54 UTC, Ritesh-Udgata commented
Ok i will come up with some better idea in the future. For now i am closing this pull request.

2024-11-01 06:54 UTC, closed without merging